### ISSUE TITLE
Twitter account / feeds issues 

### ISSUE THREAD

**Issue by Karmak23** [1flow/1flow#35]
There are still some rough corners in the twitter features.
The most visible are crashes in the workers when an account is disconnected.

Eg.

- connect an account
  - this creates the timeline and lists
- workers start to fetch
- user disconnects his/her account
  - this should remove associated timeline / lists
- the running fetchers don't stop
- when they release the account, they crash:

```
[2015-03-03 15:04:20,699: ERROR/Worker-581] exception while running consume on TwitterFeed #612
Traceback (most recent call last):
  File "/home/1flow/www/src/oneflow/base/utils/__init__.py", line 172, in task_func
    result = getattr(objekt, method_name)(*args, **kwargs)
  File "/home/1flow/www/src/oneflow/core/models/reldb/feed/twitter.py", line 836, in consume
    self.__consume_items('lists/statuses', parameters)
  File "/home/1flow/www/src/oneflow/core/models/reldb/feed/twitter.py", line 618, in __consume_items
    with twitter_account as tweetapi:
AttributeError: __exit__
```

Client side, the user sees nothing problematic, but the twitter feature needs some love to polish it.

**Comment by Karmak23** [comment]
Some of the issues are adressed in current versions, notably when a twitter list / account has been removed while a worker is consuming for/from it. Other issues still need to be addressed.
